### ISSUE TITLE
Suggestions on Kubernetes deployment approach

### ISSUE THREAD

**Issue by fprivero** [bcanvural/brxm-separate-authoring-delivery#1]
Hi @bcanvural, thanks for this repo and for [the wonderful article that comes with it](https://developers.bloomreach.com/blog/2020/deploy-brxm-authoring-and-delivery-apps-separately-with-docker-compose-or-kubernetes.html).

I'm trying to setup this in a Kubernetes cluster. I would like to get some insight from you on what would be the best way to solve the issue of having to make sure the authoring instances are in place before the delivery ones start.

In your article you described how to do the same in docker-compose using the `depends_on` feature and the `/brxm/curl_till_200.sh` sh script.

Do you have any suggestions for the Kubernetes deployments?

Thanks in advance

**Comment by bcanvural** [comment]
Thanks for your kind words :) I don't remember if the requirement to have the delivery wait on authoring is still there. It's been a while since I wrote the article and I don't work daily with developing brxm anymore.
As i was writing this, I found one of the platform engineers and asked him directly. That requirement is not there anymore apparently. So do try it out and let's see how it goes!

**Comment by bcanvural** [comment]
Otherwise probably you could use initcontainers or embed the script in the delivery app but it would be way more complicated than it looks

**Comment by fprivero** [comment]
I should have started by saying that I'm using version 14 (enterprise) and I can confirm that if I don't wait for the authoring instance to start the delivery one, the repository gets into an inconsistent state. 

Right now I'm using a nasty workaround using initContainers introducing a forced delay of X seconds for the delivery instances start. I was trying to do something with the healthcheck of the authoring pod, but I have not managed to get it to work.

Maybe this is something that version 15 solves? It is still clearly specified [in the docs](https://xmdocumentation.bloomreach.com/library/enterprise/installation-and-configuration/separate-hst-deployment-model.html) that one should be started before the other.

Sorry to bother you with this, and again thanks for any direction you could provide.

**Comment by bcanvural** [comment]
Hmm ok interesting apparently that's still important. Did you try something like hitting the http://authoring:8080/cms/ping/  in the initcontainers script? (assuming you have a service named authoring pointing to cms pods?). also note that you have to have a "/" at the end of the /cms/ping/

**Comment by fprivero** [comment]
Hey sorry for the late reply, yeah I have tried the `initContainers` now after your suggestion. It is working. Thanks!

**Comment by bcanvural** [comment]
Glad it works! Thanks for sharing
